name: Azure VM Bicep Deployment

on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy-vm:
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use v4 for the latest features and security fixes

      - name: Azure Login
        uses: azure/login@v2 # Authenticate to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Your Azure Service Principal credentials
          # Output the subscription ID from the login action
          # This assumes your service principal is scoped to a single subscription.
          # If it has access to multiple, you might need to specify it in the creds.
          # For now, let's assume the default behavior is sufficient.
          # We'll use an output variable to capture it.
          # Output format is usually login_result.subscriptionId but for this action,
          # it often automatically uses the logged-in context for subsequent actions.
          # However, explicitly passing it is better practice.

      - name: Debug - List Files in VM directory (Optional, for troubleshooting)
        run: ls -l VM/

      - name: Deploy Azure VM using Bicep and Parameter File
        uses: azure/bicep-deploy@v1 # Using the dedicated bicep-deploy action (v1)
        with:
          type: 'deployment' # Specifies a standard ARM/Bicep deployment
          operation: 'create' # Specify the deployment operation for creating/updating
          scope: 'resourcegroup' # Specify the scope of the deployment

          # --- ADDED: The required 'subscription-id' input ---
          # This typically comes from the AZURE_CREDENTIALS secret or an Azure CLI command.
          # The simplest way is often to retrieve it via an Azure CLI command after login.
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Assuming you have this secret

          resource-group-name: RG-WebApplication # Your target Azure Resource Group
          template-file: ./VM/azuredeploycustomconfiguration.bicep # Path to your Bicep template
          parameters-file: ./VM/azuredeploycustomconfiguration.parameters.json # Path to your JSON parameter file
          parameters: '{"adminPassword": "${{ secrets.VM_ADMIN_PASSWORD }}"}' # Inline override for the secret password