name: Azure VM Bicep Deployment

on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy-vm:
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use v4 for the latest features and security fixes

      - name: Azure Login
        id: az_login # <--- ADD AN ID HERE to reference its outputs
        uses: azure/login@v2 # Authenticate to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Your Azure Service Principal credentials

      - name: Debug - List Files in VM directory (Optional, for troubleshooting)
        run: ls -l VM/

      - name: Deploy Azure VM using Bicep and Parameter File
        uses: azure/bicep-deploy@v1 # Using the dedicated bicep-deploy action (v1)
        with:
          type: 'deployment' # Specifies a standard ARM/Bicep deployment
          operation: 'create' # Specify the deployment operation for creating/updating
          scope: 'resourceGroup' # Specify the scope of the deployment

          # --- CRITICAL CORRECTION: Get subscription-id from the azure/login output ---
          # The azure/login action (v2 and higher) outputs 'subscriptionId'
          subscription-id: ${{ steps.az_login.outputs.subscriptionId }}

          resource-group-name: RG-WebApplication # Your target Azure Resource Group
          template-file: ./VM/azuredeploycustomconfiguration.bicep # Path to your Bicep template
          parameters-file: ./VM/azuredeploycustomconfiguration.parameters.json # Path to your JSON parameter file
          parameters: '{"adminPassword": "${{ secrets.VM_ADMIN_PASSWORD }}"}' # Inline override for the secret password