name: Azure VM Bicep Deployment

on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy-vm:
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use v4 for the latest features and security fixes

      - name: Azure Login
        uses: azure/login@v2 # Authenticate to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Your Azure Service Principal credentials

      - name: Debug - List Files in VM directory (Optional, for troubleshooting)
        run: ls -l VM/

      - name: Deploy Azure VM using Bicep and Parameter File
        uses: azure/bicep-deploy@v1 # Using the dedicated bicep-deploy action (v1)
        with:
          type: 'deployment' # Specifies a standard ARM/Bicep deployment
          resource-group-name: RG-WebApplication # Your target Azure Resource Group
          template-file: ./VM/azuredeploycustomconfiguration.bicep # Path to your Bicep template

          # --- CORRECTED: Use 'parameters-file' for the JSON file ---
          parameters-file: ./VM/azuredeploycustomconfiguration.parameters.json

          # --- CORRECTED: Use 'parameters' ONLY for inline JSON overrides ---
          # This must be a single-line valid JSON string.
          parameters: '{"adminPassword": "${{ secrets.VM_ADMIN_PASSWORD }}"}'

          # --- REMOVED: 'additional-arguments' is NOT a valid input for this action ---
          # (It was already removed in the previous attempt, but just confirming it's absent here)