name: Azure VM Bicep Deployment

on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy-vm:
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use v4 for the latest features and security fixes

      - name: Azure Login
        uses: azure/login@v2 # Authenticate to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Your Azure Service Principal credentials

      - name: Debug - List Files in VM directory (Optional, for troubleshooting)
        run: ls -l VM/

      - name: Deploy Azure VM using Bicep and Parameter File
        uses: azure/arm-deploy@v3 # CORRECTED: Using v3 as v4 does not exist
        with:
          resourceGroupName: RG-WebApplication # Your target Azure Resource Group
          template: ./VM/azuredeploycustomconfiguration.bicep # Path to your Bicep template
          # Use a multi-line string for parameters to combine file and overrides
          parameters: |
            ./VM/azuredeploycustomconfiguration.parameters.json
            adminPassword=${{ secrets.VM_ADMIN_PASSWORD }} # Override password from GitHub Secret
          failOnStdErr: true # Fail the workflow step if any stderr output occurs
        env:
          AZURE_CLI_DEBUG: true # Enable debug logging for Azure CLI commands within this step