name: Deploy Public Load Balancer

on:
  workflow_dispatch:
    inputs:
      public_ip_address_name:
        description: 'Name of the Public IP Address'
        required: true
        
      public_load_balancer_name:
        description: 'Location of the Public LoadBalancer'
        required: true
           
      resource_group:
        description: 'ResourceGroup for the LoadBalancer'
        required: true     

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a Linux runner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Azure Login
      uses: azure/login@v1 # Action to log in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # GitHub Secret containing Azure Service Principal credentials
        
    - name: Debug - Print Environment Variables
      run: |
        echo "PUBLIC_IP_ADDRESS_NAME: ${{ github.event.inputs.public_ip_address_name }}"
        echo "PUBLIC_LOAD_BALANCER_NAME: ${{ github.event.inputs.public_load_balancer_name }}"
        echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS }}"
        
    - name: Deploy Resource Group
      uses: azure/arm-deploy@v1 # Action to deploy an ARM template
      with:
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }} # GitHub Secret for your Azure Subscription ID
        resourceGroupName: ${{ github.event.inputs.resource_group }}
        template: ./LB/createPublicLoadBalancer.json # Path to your ARM template file
        parameters: > # Parameters for your ARM template
          public_lb_name=${{ github.event.inputs.public_load_balancer_name }}
          public_ip_name=${{ github.event.inputs.public_ip_address_name }}
        failOnStdErr: true # Fail the workflow if there are errors in the deployment output    
