name: Deploy Azure Resource Group

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the main branch

env:
  AZURE_RESOURCE_GROUP_NAME: training8 # Replace with your desired resource group name
  AZURE_RESOURCE_GROUP_LOCATION: eastus # Replace with your desired Azure region

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Azure Login
      uses: azure/login@v1 # Action to log in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # GitHub Secret containing Azure Service Principal credentials
        
    - name: Debug - Print Environment Variables
      run: |
        echo "AZURE_RESOURCE_GROUP_NAME: ${{ env.AZURE_RESOURCE_GROUP_NAME }}"
        echo "AZURE_RESOURCE_GROUP_LOCATION: ${{ env.AZURE_RESOURCE_GROUP_LOCATION }}"
        echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS }}"
        
    - name: Deploy Resource Group
      uses: azure/arm-deploy@v1 # Action to deploy an ARM template
      with:
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }} # GitHub Secret for your Azure Subscription ID
        scope: subscription # <--- IMPORTANT CHANGE: Deploy at the subscription level
        location: eastus # <--- IMPORTANT CHANGE: Location for the deployment operation
        template: ./resourceGroup.json # Path to your ARM template file
        parameters: > # Parameters for your ARM template
          resourceGroupName=${{ env.AZURE_RESOURCE_GROUP_NAME }}
          resourceGroupLocation=${{ env.AZURE_RESOURCE_GROUP_LOCATION }}
        failOnStdErr: true # Fail the workflow if there are errors in the deployment outpu
