name: Deploy Public IP Address

on:
  workflow_dispatch:
  inputs:
    public_ip_address_name:
        description: 'Name of the Public IP Address'
        required: true
        
    public_ip_address_location:
        description: 'Location of the Public IP Address'
        required: true
        default: 'eastus'
        
    public_ip_address_sku:
        description: 'SKU of the Public IP Address'
        required: true
        default: 'Standard'    

    public_ip_address_allocation_method:
        description: 'Allocation method of the Public IP Address'
        required: true
        default: 'Static'  
      
    resource_group:
        description: 'ResourceGroup for the Storage Account'
        required: true     

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a Linux runner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Azure Login
      uses: azure/login@v1 # Action to log in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # GitHub Secret containing Azure Service Principal credentials
        
    - name: Debug - Print Environment Variables
      run: |
        echo "PUBLIC_IP_ADDRESS_NAME: ${{ github.event.inputs.storage_name }}"
        echo "PUBLIC_IP_ADDRESSLOCATION: ${{ github.event.inputs.storage_location }}"
        echo "PUBLIC_IP_ADDRESS_SKU: ${{ github.event.inputs.storage_sku }}"
        echo "PUBLIC_IP_ADDRESS_ALLOCATION_METHOD: ${{ github.event.inputs.storage_sku }}"
        echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS }}"
        
    - name: Deploy Resource Group
      uses: azure/arm-deploy@v1 # Action to deploy an ARM template
      with:
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }} # GitHub Secret for your Azure Subscription ID
        resourceGroupName: ${{ github.event.inputs.resource_group }}
        template: ./LB/createPublicIpAddress.json # Path to your ARM template file
        parameters: > # Parameters for your ARM template
          name=${{ github.event.inputs.public_ip_address_name }}
          location=${{ public_ip_address_location }}
          SKU=${{ public_ip_address_sku }}
          publicIPAllocationMethod=${{public_ip_address_allocation_method }}
        failOnStdErr: true # Fail the workflow if there are errors in the deployment output    
