name: Deploy VM (chained from RG)

on:
  workflow_dispatch:
    inputs:
      vmName:
        description: 'VM Name'
        required: true
        default: 'trainingvm'
      adminUsername:
        description: 'Admin username'
        required: true
        default: 'azureuser'
      adminPassword:
        description: 'Admin password'
        required: true
      resourceGroupName:
        description: 'Resource Group Name'
        required: true
        default: 'training8'
      location:
        description: 'Location'
        required: true
        default: 'eastus'

jobs:
  create-resource-group:
    uses: ./.github/workflows/resource-group.yml
    with:
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      resourceGroupLocation: ${{ github.event.inputs.location }}

  deploy-vm:
    needs: create-resource-group
    runs-on: ubuntu-latest
    environment:
      name: manual-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          template: ./VM/azuredeploycustomconfiguration.json
          parameters: >
            vmName=${{ github.event.inputs.vmName }}
            adminUsername=${{ github.event.inputs.adminUsername }}
            adminPassword=${{ github.event.inputs.adminPassword }}

